trigger:
  branches:
    include:
      - main

variables:
  imageName: 'frontend'
  acrName: 'myacr.azurecr.io'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: $(acrName)/$(imageName)
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToK8s
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-connection'
        namespace: 'default'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'charts/frontend'
        releaseName: 'frontend'
        overrideValues: |
          image.repository=$(acrName)/$(imageName)
          image.tag=$(Build.BuildId)
